all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-54-184-30-165.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-34-210-72-249.us-west-2.compute.amazonaws.com
